# Generated by Django 5.2 on 2025-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Уникальный идентификатор чата",
            ),
        ),
    ]
