# Generated by Django 5.2 on 2025-04-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_profile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Ник в Telegram"
            ),
        ),
    ]
