# Generated by Django 5.2 on 2025-04-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название привычки"),
                ),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "action",
                    models.CharField(max_length=300, verbose_name="Описание привычки"),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Периодичность"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        max_length=300, verbose_name="Вознаграждение за выполнение"
                    ),
                ),
                (
                    "time_to_complete",
                    models.DurationField(verbose_name="Время на выполнение привычки"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
